[IoTtalk]
#ServerIP = 140.113.199.182
ServerIP = 140.113.215.10
Port = 9999
version = 1

[env]
LogRoot = ./logs
host = 0.0.0.0
port = 7789
host_ag = 140.113.215.12
port_ag = 8000
port_zmq = 7790
icon_path = ./static/imgs
default_icon = 0_landscape.svg
icon_extensions = png,svg


[db]
database = mysql
host = 140.113.215.12
port = 3306
user = cbsubsystem
pwd = pcs54784
dbname = controlboard