[IoTtalk]
# IoTtalk Server IP
ServerIP = 140.113.215.10

# IoTtalk Server Port
Port = 9999

# Use v1 or v2
version = 1

[env]
# Root directory to save logs.
LogRoot = ./logs

# CB Subsystem's Public IP address.
# host = 140.113.63.25
host = 140.113.215.10

# CB Subsystem's port.
port = 7789

# AG Subsystem's Public IP address.
host_ag = 140.113.215.10

# AG Subsystem's port.
port_ag = 8080
port_zmq = 7790



# Root directory to save custom icons.
icon_path = ./static/imgs

# Default ControlBoard icon.
default_icon = 0_landscape.svg

# Accepted icon extensions.
icon_extensions = png,svg

# Default Admin account
admin = admin

[db]
# use MySQL or SQLlite
database = mysql

# MySQL Server IP
host = 140.113.215.10

# MySQL Server Port
port = 3306

# User name for MySQL Server
user = CB

# Password for MySQL Server
pwd = pcs54784

# DB name for MySQL Server
dbname = controlboard

# Whether to reset db, 0 or 1
reset = 0