[IoTtalk]
# IoTtalk Server IP
ServerIP = sdwanccm.iottalk.tw

# IoTtalk Server Port
Port = 443

# Use v1 or v2
version = 1

[env]
# Root directory to save logs.
LogRoot = ./logs

# CB Subsystem's Public IP address.
host = 0.0.0.0

# CB Subsystem's port.
port = 7789

# AG Subsystem's Public IP address.
host_ag = 0.0.0.0

# AG Subsystem's port.
port_ag = 8888

# Port for SA Status Collector
port_zmq = 7794

# Root directory to save custom icons.
icon_path = ./static/imgs

# Default ControlBoard icon.
default_icon = 0_landscape.svg

# Accepted icon extensions.
icon_extensions = png,svg

# Email Notifier Sender
sender = ControlBoard@iottalk.tw

# Email Title
title = Manual operation notification

[MQTT]
MQTT_broker = None
MQTT_port = 6688
MQTT_encryption = False
MQTT_User = iottalk
MQTT_PW = iottalk2023

[db]
# use mysql or sqlite
database = sqlite

# MySQL Server IP
host = 140.113.215.12

# MySQL Server Port
port = 3306

# User name for MySQL Server
user = cbsubsystem

# Password for MySQL Server
pwd = pcs54784

# DB name for MySQL Server
dbname = controlboard

# Whether to reset db, 0 or 1
reset = 0

[oauth]
client_id = ezZVh77CDIqG4Wz6g36pqJ7t3DRB7Tu3Et34QPLo
client_secret = 7oWU9cduOcSJjwpRrAx8JZVPWCMjeyDwUiy5F0mxYkdvKY1MLkATX04FCJpt9vqfmjLlAJNxaUdm4eul670b07dQO0kk1Z9DSOKt0e7YqAz7M7W5iGK8vNpecBnazWwtF2gU9fXJHFmxzXRoaxSFGDd086a2mhlk
openid_url = https://account.cb.iottalk.tw/.well-known/openid-configuration